name: Clippy check
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  clippy_check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - run: rustup component add clippy

      - name: Run clippy manually without annotations
        run: cargo clippy --all-targets -- -D warnings